name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: npm i
        env:
          CI: true

      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        run: npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}
